# Generated by Django 2.1 on 2021-01-02 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('milestone', models.FloatField(default=0)),
                ('thumbnail_url', models.CharField(default='http://superrace.herokuapp.com/static/anh.png', max_length=2048)),
                ('no_runners', models.IntegerField(default=0)),
                ('total_distance', models.FloatField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='back_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
