# Generated by Django 2.1 on 2021-01-02 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('duration', models.TimeField()),
                ('distance', models.FloatField(default=0)),
                ('pace', models.FloatField(default=0)),
                ('caption', models.CharField(max_length=1024)),
                ('image_url', models.CharField(default='http://superrace.herokuapp.com/static/anh.png', max_length=2048)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
