# Generated by Django 2.1 on 2021-01-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinevent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinevent',
            name='date_left',
            field=models.DateField(auto_now=True),
        ),
    ]
